# This file is generated by device/motorola/motus/extract-files.sh - DO NOT EDIT
PRODUCT_COPY_FILES += \
    vendor/motorola/motus/proprietary/lib/libgps.so:obj/lib/libgps.so

# All the blobs necessary for motus
PRODUCT_COPY_FILES += \
    vendor/motorola/motus/proprietary/root/factory.rle:root/factory.rle \
    vendor/motorola/motus/proprietary/root/initlogo.rle:root/initlogo.rle \
    vendor/motorola/motus/proprietary/root/logo.rle:root/logo.rle \
    vendor/motorola/motus/proprietary/sbin/charge_only_mode:root/sbin/charge_only_mode \
    vendor/motorola/motus/prebuilt/lib/libnativetask.so:system/lib/libnativetask.so \
    vendor/motorola/motus/prebuilt/lib/libwtnativetask.so:system/lib/libwtnativetask.so \
    vendor/motorola/motus/prebuilt/app/WirelessTether.apk:system/app/WirelessTether.apk \
    vendor/motorola/motus/prebuilt/etc/akmd_set.txt:system/etc/akmd_set.txt \
    vendor/motorola/motus/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/motorola/motus/proprietary/bin/touchpad:system/bin/touchpad \
    vendor/motorola/motus/proprietary/bin/minipadut:system/bin/minipadut \
    vendor/motorola/motus/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/motorola/motus/proprietary/bin/fuel_gauge:system/bin/fuel_gauge \
    vendor/motorola/motus/proprietary/bin/port_bridge:system/bin/port_bridge \
    vendor/motorola/motus/proprietary/bin/tcmd_engine:system/bin/tcmd_engine \
    vendor/motorola/motus/proprietary/bin/tcmd_sql:system/bin/tcmd_sql \
    vendor/motorola/motus/proprietary/etc/akm/akmd_set.cfg:system/etc/akm/akmd_set.cfg \
    vendor/motorola/motus/proprietary/etc/touchpad/touchpad.enc:system/etc/touchpad/50/touchpad.enc \
    vendor/motorola/motus/proprietary/etc/touchpad/touchpad.cfg:system/etc/touchpad/50/touchpad.cfg \
    vendor/motorola/motus/proprietary/etc/touchpad/saveconfig.cfg:system/etc/touchpad/50/saveconfig.cfg \
    vendor/motorola/motus/proprietary/etc/minipad/minipad.cfg:system/etc/minipad/104/minipad.cfg \
    vendor/motorola/motus/proprietary/etc/minipad/minipad.enc:system/etc/minipad/104/minipad.enc \
    vendor/motorola/motus/proprietary/etc/minipad/saveconfig.cfg:system/etc/minipad/104/saveconfig.cfg \
    vendor/motorola/motus/proprietary/etc/fuel_gauge/0006.dffs:system/etc/fuel_gauge/0006.dffs \
    vendor/motorola/motus/proprietary/etc/fuel_gauge/0301.bqfs:system/etc/fuel_gauge/0301.bqfs \
    vendor/motorola/motus/proprietary/etc/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/motorola/motus/proprietary/etc/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/motorola/motus/proprietary/etc/firmware/bcm4325.hcd:system/etc/firmware/bcm4325.hcd \
    vendor/motorola/motus/proprietary/etc/firmware/fw_bcm4325.bin:system/etc/firmware/fw_bcm4325.bin \
    vendor/motorola/motus/proprietary/etc/firmware/fw_bcm4325_apsta.bin:system/etc/firmware/fw_bcm4325_apsta.bin \
    vendor/motorola/motus/proprietary/etc/firmware/nvram.txt:system/etc/firmware/nvram.txt \
    vendor/motorola/motus/proprietary/lib/egl/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \
    vendor/motorola/motus/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/motorola/motus/proprietary/lib/libril-moto-umts-1.so:system/lib/libril-moto-umts-1.so \
    vendor/motorola/motus/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/motorola/motus/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/motorola/motus/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/motorola/motus/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/motorola/motus/proprietary/lib/libsnd.so:system/lib/libsnd.so \
    vendor/motorola/motus/proprietary/lib/libmotdb.so:system/lib/libmotdb.so \
    vendor/motorola/motus/proprietary/lib/libgki.so:system/lib/libgki.so \
    vendor/motorola/motus/proprietary/lib/libmsl_interface.so:system/lib/libmsl_interface.so \
    vendor/motorola/motus/proprietary/lib/libtpa_core.so:system/lib/libtpa_core.so \
    vendor/motorola/motus/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/motorola/motus/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/motorola/motus/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/motorola/motus/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/motorola/motus/proprietary/lib/libgps.so:system/lib/libgps.so \
    vendor/motorola/motus/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/motorola/motus/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/motorola/motus/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/motorola/motus/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/motorola/motus/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/motorola/motus/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/motorola/motus/proprietary/lib/libmmcamera.so:system/lib/libmmcamera.so \
    vendor/motorola/motus/proprietary/lib/libmm-qcamera-tgt.so:system/lib/libmm-qcamera-tgt.so \
    vendor/motorola/motus/proprietary/lib/libhpprop.so:system/lib/libhpprop.so \
    vendor/motorola/motus/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/motorola/motus/proprietary/lib/libomx_arcomxcore_sharedlibrary.so:system/lib/libomx_arcomxcore_sharedlibrary.so \
    vendor/motorola/motus/proprietary/lib/libomx_wmadec_sharedlibrary.so:system/lib/libomx_wmadec_sharedlibrary.so \
    vendor/motorola/motus/proprietary/lib/libomx_wmvdec_sharedlibrary.so:system/lib/libomx_wmvdec_sharedlibrary.so \
    vendor/motorola/motus/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/motorola/motus/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/motorola/motus/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/motorola/motus/proprietary/lib/hw/sensors.msm7k.so:system/lib/hw/sensors.msm7k.so
